-- Auto-generated from schema-map-postgres.yaml (map@sha1:F0EE237771FBA8DD7C4E886FF276F91A862C3718)
-- engine: postgres
-- table:  rate_limit_counters

CREATE TABLE IF NOT EXISTS rate_limit_counters (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  subject_type TEXT NOT NULL,
  subject_id   VARCHAR(128) NOT NULL,
  name         VARCHAR(120) NOT NULL,
  window_start TIMESTAMPTZ(6) NOT NULL,
  window_size_sec INTEGER NOT NULL,
  "count" INTEGER NOT NULL DEFAULT 0,
  updated_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  CONSTRAINT uq_rlc UNIQUE (subject_type, subject_id, name, window_start, window_size_sec)
);
